image: "pmem/pmdk:1.7-fedora-28"

stages:
  - build
  - test

before_script:
  - echo pmdkpass | sudo -S dnf update -y
  - echo pmdkpass | sudo -S dnf install -y cmake
  - echo pmdkpass | sudo -S mkdir -p /mnt/pmem/test
  - echo pmdkpass | sudo -S chmod 777 /mnt/pmem/test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../src
    - make -j

test:
  stage: test
  script:
    - ctest

