image: "pmem/pmdk:1.7-fedora-28"

stages:
  - build
  - test

before_script:
  - whoami
  - dnf update -y
  - mkdir -p /mnt/pmem/test
  - chmod 777 /mnt/pmem/test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../src
    - make -j

test:
  stage: test
  script:
    - ctest

