image: "pmem/pmdk:1.7-fedora-28"

stages:
  - build
  - test

before_script:
  - su root -c "dnf update -y"
  - su root -c "mkdir -p /mnt/pmem/test"
  - su root -c "chmod 777 /mnt/pmem/test"

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../src
    - make -j

test:
  stage: test
  script:
    - ctest

