image: "pmem/libpmemobj-cpp:fedora-30"

stages:
  - build
  - test

before_script:
#    - echo pass | sudo -S dnf update -y
  - echo pass | sudo -S dnf install -y cmake libpmemobj++-devel

build:
  stage: build
  script:
    - ls -l /usr/lib64/libpmem*
    - ls -l /usr/include/libpmem*
    - pwd
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_FLAGS="-g -O0 -Wall -fprofile-arcs -ftest-coverage" ../src
    - make -j
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo pass | sudo -S mkdir -m 777 -p /mnt/pmem/test
    - cd build
    - ctest
  dependencies:
    - build

