image: "pmem/libpmemobj-cpp:fedora-30"

stages:
  - build
  - test

before_script:
#  - echo pass | sudo -S dnf update -y
  - echo pass | sudo -S dnf install -y cmake
  - echo pass | sudo -S dnf install -y libpmemobj++-devel
  - echo pass | sudo -S mkdir -p /mnt/pmem/test
  - echo pass | sudo -S chmod 777 /mnt/pmem/test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../src
    - make -j

test:
  stage: test
  script:
    - ctest

