image: "dbisilm/nvm-based_data_structures:latest"

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_FLAGS="-g -O0 -fprofile-arcs -ftest-coverage" ../src
    - make -j
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo pass | sudo -S mkdir -m 777 -p /mnt/pmem/test
    - cd build
    - ctest
  dependencies:
    - build

