image: "dbisilm/nvm-based_data_structures:latest"

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -O0 -fprofile-arcs -ftest-coverage" ../src
    - make
    # clean up unnecessary files and strip binaries
    - rm -rf _deps *tree generated
    - strip bench/point bench/scan bench/tree_* test/*Test
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo pass | sudo -S mkdir -m 777 -p /mnt/pmem/test
    - cd build
    - ctest
  dependencies:
    - build

