image: "pmem/pmdk:1.7-fedora-28"

stages:
  - build
  - test

before_script:
  - sudo dnf update -y
  - sudo mkdir -p /mnt/pmem/test
  - sudo chmod 777 /mnt/pmem/test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../src
    - make -j

test:
  stage: test
  script:
    - ctest

